name: CI-Custom-Arch

on:
  workflow_dispatch: # Để bạn bấm nút chạy tay

jobs:
  release-setup:
    # Giữ lại job này vì build-archlinux cần "outputs" từ nó
    uses: LizardByte/.github/.github/workflows/__call-github-env.yml@master
    
  build-archlinux:
    name: Archlinux
    needs: release-setup
    permissions:
      contents: read
    uses: ./.github/workflows/ci-archlinux.yml
    with:
       release_commit: ${{ needs.release-setup.outputs.release_commit }}
       release_version: ${{ needs.release-setup.outputs.release_version }}
